version: "3.7"
services:
  todolist-rest-api:
    container_name: todolist-rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./

  cadd:
    image: caddy/caddy:2.6.3-alpine
    container_name: caddy-services
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/services
      - caddy_data:/data
      - caddy_config:/config

  volumes:
    caddy_data:
    caddy_config:
